### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by johaw** [yamanyar/restrict-maven-plugin#11]
It would be nice if this had a standard opensource license like MIT or Apache License 2.0

**Comment by seanf** [comment]
Intended to be ASL 2.0, I suppose? 

https://github.com/yamanyar/restrict-maven-plugin/blob/master/pom.xml#L19

**Comment by johaw** [comment]
@seanf Woops, I was looking for a license file at the root directory and didn't notice the one in the pom.xml.  Thanks.

**Comment by seanf** [comment]
I do think it would be a good idea to put a copy of the intended licence text in the repo, plus a mention in the README. 

https://wiki.opensource.org/bin/Main/Projects/OSI+Website+Page+Improvements/How+to+apply+an+open+source+license+to+your+project/
