### ISSUE TITLE
allow to inspect only buildDirectory

### ISSUE THREAD

**Issue by jozic** [yamanyar/restrict-maven-plugin#4]
now the plugin does this
```
                inspector.inspectArtifacts(artifacts);
                inspector.inspectFolder(buildDirectory);
```

there should be a parameter like inspectDependencies, which can be set to `false`. And plugins will just do `inspector.inspectFolder(buildDirectory)` in this case

**Comment by yamanyar** [comment]
Maybe you do no need anymore; but i implemented this feature and will be available in 0.8

**Comment by yamanyar** [comment]
0.8 is released. See readme to ignore it

**Comment by jozic** [comment]
cool, thanks!
