### ISSUE TITLE
flag to skip the plugin

### ISSUE THREAD

**Issue by caarlos0** [yamanyar/restrict-maven-plugin#6]
Sometimes I just don't care about restrictions, I just want to package something fast for some testing purpose.

It would be nice to have a flag to skip restrict-maven-plugin execution, like, `-Drestrict.skip`

What do you think?

**Comment by yamanyar** [comment]
Hi,

Good idea; i will implement that

**Comment by yamanyar** [comment]
I implemented it. You will be able to use that in 0.8.

**Comment by yamanyar** [comment]
0.8 is released

**Comment by caarlos0** [comment]
@yamanyar thanks! :D
