### ISSUE TITLE
Maybe release 0.7?

### ISSUE THREAD

**Issue by twz123** [yamanyar/restrict-maven-plugin#8]
Hi,

first of all, thanks for this nice plugin!

Since the current master has some improvements compared to v0.6, do you plan to release a new fixed version of this to maven central any time soon?

Cheers
Tom

**Comment by yamanyar** [comment]
Hi,

It has been long time I have not find chance to use Java in my projects. I released a snapshot but could not find chance to test it.

<dependency>
  <groupId>com.yamanyar</groupId>
  <artifactId>restrict-maven-plugin</artifactId>
  <version>0.7-SNAPSHOT</version>
</dependency>

Can you help me to test; if it seems ok; we can release it.

https://oss.sonatype.org/index.html#view-repositories;snapshots~browsestorage~/com/yamanyar/restrict-maven-plugin/0.7-SNAPSHOT/restrict-maven-plugin-0.7-20150720.063644-1.jar

**Comment by twz123** [comment]
Thanks for your reply!

We're using the current master version for one week now without any issues. So it's not thoroughly tested, but at least nothing obvious wrong with it.

**Comment by yamanyar** [comment]
Thank you too.

0.7 is released:
http://repo1.maven.org/maven2/com/yamanyar/restrict-maven-plugin/0.7/

**Comment by yamanyar** [comment]
Once started, I tried to close as much issues as possible; so 0.8 is also available

**Comment by twz123** [comment]
Cool ;)
